export const GET_MOVIE_LIST_REQUEST = 'GET_MOVIE_LIST_REQUEST';
export const GET_MOVIE_LIST_SUCCESS = 'GET_MOVIE_LIST_SUCCESS';
export const GET_MOVIE_LIST_ERROR = 'GET_MOVIE_LIST_ERROR';

export const POST_CREATE_NEW_MOVIE_REQUEST = 'POST_CREATE_NEW_MOVIE_REQUEST';
export const POST_CREATE_NEW_MOVIE_SUCCESS = 'POST_CREATE_NEW_MOVIE_SUCCESS';
export const POST_CREATE_NEW_MOVIE_ERROR = 'POST_CREATE_NEW_MOVIE_ERROR';
